services:
  todo-web-api:
    image: ${DOCKER_REGISTRY-}todowebapi
    container_name: todo-web-api
    build:
      context: .
      dockerfile: src/Todo.Web.Api/Dockerfile
    ports:
      - 5000:8080

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=todo-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/.docker-conf/staging/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80