services:
  todo-web-api:
    image: ${DOCKER_REGISTRY-}todowebapi
    build:
      context: .
      dockerfile: src/Todo.Web.Api/Dockerfile
    ports:
      - 5000:8080

  todo-db:
    image: postgres:latest
    container_name: todo_database
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/.docker-conf/staging/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  todo-seq:
    image: datalust/seq:latest
    container_name: todo_seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80